"""initial_schema

Revision ID: e35207fe4427
Revises: 
Create Date: 2025-12-11 18:01:15.167293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35207fe4427'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('claude_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_country_code', sa.String(length=10), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county_state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('base_cv_content', sa.Text(), nullable=True),
    sa.Column('base_cv_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('email_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'OUTLOOK', name='emailprovider'), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_email_id', sa.String(length=255), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_summary', sa.Text(), nullable=True),
    sa.Column('requirements_extracted', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('skills_matched', sa.JSON(), nullable=True),
    sa.Column('skills_missing', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('INBOX', 'INTERESTING', 'ADAPTED', 'READY', 'APPLIED', 'BLOCKED', 'REJECTED', 'ARCHIVED', name='jobstatus'), nullable=True),
    sa.Column('blocker_type', sa.Enum('CAPTCHA', 'FILE_UPLOAD', 'LOGIN_REQUIRED', 'MULTI_STEP_FORM', 'LOCATION_MISMATCH', 'NONE', name='blockertype'), nullable=True),
    sa.Column('blocker_details', sa.Text(), nullable=True),
    sa.Column('ats_type', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('ASSISTED', 'SEMI_AUTO', 'AUTO', name='applicationmode'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUBMITTED', 'FAILED', 'NEEDS_INTERVENTION', name='applicationstatus'), nullable=True),
    sa.Column('form_fields_filled', sa.JSON(), nullable=True),
    sa.Column('form_questions_answered', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('browser_session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('material_type', sa.Enum('CV', 'COVER_LETTER', 'TALKING_POINTS', name='materialtype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('changes_made', sa.JSON(), nullable=True),
    sa.Column('changes_explanation', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_discoveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('source_job_id', sa.UUID(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('should_include_in_cv', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_discoveries')
    op.drop_table('materials')
    op.drop_table('applications')
    op.drop_table('jobs')
    op.drop_table('email_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
